# Basic Array

In [2]:
import numpy as np

In [3]:
array0 = np.array([1, 2, 3])
array1 = np.array([4, 5, 6])
array2 = np.array([[1, 2], [3, 4]])

#### How to make user insert numbers for array

arr2 = np.array(list(map(int, input().split())))

In [4]:
array3 = array0 + array1
print(array3)

[5 7 9]


In [5]:
array4 = np.array([10, 20, 30, 40, 50])

In [6]:
greater_than_25 = array4 > 25
print(greater_than_25)

[False False  True  True  True]


In [7]:
filtered_arr = array4[greater_than_25]
print(filtered_arr)


[30 40 50]


In [8]:
array5 = array4[0:5]
print(array5, "\n")
array6 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array5 = array4[:3]
print(array5)

[10 20 30 40 50] 

[10 20 30]


In [9]:
arrH0 = np.random.randint(100, 199, size=(4, 5))
arrH0

array([[192, 151, 182, 170, 190],
       [164, 189, 152, 132, 112],
       [171, 129, 115, 158, 160],
       [194, 172, 104, 175, 123]], dtype=int32)

In [10]:
print(arrH0[1:], "\n\n", arrH0[1:, 2:4])

[[164 189 152 132 112]
 [171 129 115 158 160]
 [194 172 104 175 123]] 

 [[152 132]
 [115 158]
 [104 175]]


In [11]:
arrH0.sum()

np.int64(3135)

In [12]:
print("", arrH0.min(), "\n", arrH0.max(), "\n", arrH0.mean(), "\n", arrH0.std())

 104 
 194 
 156.75 
 27.863730905964477


In [13]:
np.power(arrH0, 3)

array([[7077888, 3442951, 6028568, 4913000, 6859000],
       [4410944, 6751269, 3511808, 2299968, 1404928],
       [5000211, 2146689, 1520875, 3944312, 4096000],
       [7301384, 5088448, 1124864, 5359375, 1860867]], dtype=int32)

In [14]:
a = np.array([5,4,1,29,3,11,7,8])
a0, a1 = 4, 10
filter = (a > 4) & (a < 10)
filtered_array = a[filter]
print(filtered_array)

[5 7 8]


In [20]:
a = np.arange(1, 10)
matrix = a.reshape(3, 3)
matrix_swap = matrix.copy()
matrix_swap[[0, 1]] = matrix_swap[[1, 0]]

print(matrix)
print(matrix_swap)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [41]:
mat = np.arange(1, 17)
mat = mat.reshape(4, 4)

sliced_mat = mat[:2, 1:3].copy()
print(sliced_mat, mat)

[[2 3]
 [6 7]] [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [46]:
mat = np.arange(1, 10)
mat = mat.reshape(3, 3)
specific_element = mat[1, 0].copy()

print(mat)
print(specific_element)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
4


In [47]:
arr = np.array([10, 20, 30, 40, 50])
greater_than_25 = arr > 25

filtered_arr = arr[greater_than_25]
print(filtered_arr)

[False False  True  True  True]
[30 40 50]


In [62]:
a = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

sin_a = np.sin(a)

cos_complement_a = np.cos(np.pi/2 - a)

# Validate the identity (sin(x) ≈ cos(π/2 - x))
complementary_identity_check = np.allclose(sin_a, cos_complement_a)

print(a, "\n",sin_a, "\n", cos_complement_a, "\n", complementary_identity_check)

[0.         0.52359878 0.78539816 1.04719755 1.57079633] 
 [0.         0.5        0.70710678 0.8660254  1.        ] 
 [6.12323400e-17 5.00000000e-01 7.07106781e-01 8.66025404e-01
 1.00000000e+00] 
 True


In [67]:
a = np.array([np.pi/6, np.pi/4, np.pi/3, np.pi/2, np.pi])

cos_double_a = np.cos(2*a)

cosine_double_angle_identity = np.cos(a)**2 - np.sin(a)**2

identity_check = np.allclose(cosine_double_angle_identity, cos_double_a)

identity_check

True

In [68]:
arr = np.array([10,20,30,40,50])

sliced_step_values = arr[0:5:2]

a

array([10, 30, 50])

In [70]:
a = np.array([np.pi/6, np.pi/4, np.pi/3, 5*np.pi/6, 7*np.pi/6])

tan_a = np.tan(a)

cot_a = 1/tan_a

expected_cot_a = np.cos(a) / np.sin(a)
reciprocal_check = np.allclose(cot_a, expected_cot_a)

print(a, "\n", tan_a, "\n", cot_a, "\n", expected_cot_a, "\n", reciprocal_check)

[0.52359878 0.78539816 1.04719755 2.61799388 3.66519143] 
 [ 0.57735027  1.          1.73205081 -0.57735027  0.57735027] 
 [ 1.73205081  1.          0.57735027 -1.73205081  1.73205081] 
 [ 1.73205081  1.          0.57735027 -1.73205081  1.73205081] 
 True


In [71]:
age_data = np.array([25, 30, 35, 40, 45])
median_age = np.median(age_data)
median_age

np.float64(35.0)